CREATE TABLE "GCG_5727_CUST_DATA" (
 "SLNO" INTEGER DEFAULT '200000',
 "FAA_WO_NO" CHAR(10),
 "GSS_WO" CHAR(10),
 "UNIT_DESCRIPTION" CHAR(50),
 "NAME_CUSTOMER" CHAR(30),
 "ADDRESS_CUST" CHAR(50),
 "CITY_ST_ZIP_CUST" CHAR(50),
 "MAKE_MODEL" LONGVARCHAR,
 "REGISTRATION_NO" CHAR(50),
 "PART_NUMBERS" CHAR(20) );
